---
- name: Install FreeIPA server
  ansible.builtin.package:
    name:
      - freeipa-healthcheck
      - freeipa-server

- name: Copy and convert DHS CA certs
  block:
    - name: Copy DHS CA certs
      ansible.builtin.get_url:
        dest: /usr/local/share
        mode: u=rw,g=,o=
        url: https://pki.treas.gov/dhsca_fullpath.p7b
    - name: Convert P7B to PEM
      ansible.builtin.command:
        cmd: >
          openssl pkcs7 -print_certs
          -in /usr/local/share/dhsca_fullpath.p7b
          -inform DER
          -out /usr/local/share/dhsca_fullpath.pem
        creates: /usr/local/share/dhsca_fullpath.pem

- name: Copy setup script
  ansible.builtin.copy:
    dest: /usr/local/sbin
    mode: u=rx,g=,o=
    src: 00_setup_freeipa.sh

- name: >-
    Configure FreeIPA and add a systemd timer and service to disable
    inactive users
  when:
    - freeipa_disable_inactive_users
  block:
    - name: Copy inactive user setup scripts
      ansible.builtin.copy:
        dest: /usr/local/sbin
        mode: u=rx,g=,o=
        src: "{{ item }}"
      loop:
        - 01_setup_disabling_of_inactive_freeipa_users.sh
        - 02_amend_replication_agreements_and_reinitialize.sh
    - name: Copy shell script to disable inactive users
      ansible.builtin.copy:
        dest: /usr/local/sbin
        mode: u=rx,g=,o=
        src: disable_inactive_freeipa_users.sh
    - name: Copy systemd service to disable inactive users
      ansible.builtin.template:
        dest: /etc/systemd/system/disable-inactive-freeipa-users.service
        mode: u=r,g=,o=
        src: disable-inactive-freeipa-users.j2.service
        # I'd like to validate the file here, but that can't be done
        # cleanly.  See ansible/ansible#19243.
        # validate: systemd-analyze verify %s
    - name: Copy systemd timer to disable inactive users daily
      ansible.builtin.copy:
        dest: /etc/systemd/system
        mode: u=r,g=,o=
        src: disable-inactive-freeipa-users.timer
        # I'd like to validate the file here, but that can't be done
        # cleanly.  See ansible/ansible#19243.
        # validate: systemd-analyze verify %s

- name: Install Apache config fragment to disable trace functionality
  ansible.builtin.copy:
    dest: /etc/httpd/conf.d
    mode: u=rx,g=,o=
    src: disable_trace.conf
  when:
    - freeipa_disable_trace

- name: Install Apache config fragment to enable HSTS functionality
  ansible.builtin.copy:
    dest: /etc/httpd/conf.d
    mode: u=rx,g=,o=
    src: enable_hsts.conf
  when:
    - freeipa_enable_hsts
